### ISSUE TITLE
Array not working in token

### ISSUE THREAD

**Issue by BigMun** [lntel/Quickcord#1]
```
const args = content.slice(prefixResult.length).split(" ");
                                                ^

TypeError: Cannot read property 'length' of undefined
    at Client._messageEvent (C:\Users\stephen\Documents\VS Code\discordbot\node_modules\quickcord\src\client.js:83:49)
    at Client.emit (events.js:228:7)
    at MessageCreateHandler.handle (C:\Users\stephen\Documents\VS Code\discordbot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\stephen\Documents\VS Code\discordbot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\stephen\Documents\VS Code\discordbot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\stephen\Documents\VS Code\discordbot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\stephen\Documents\VS Code\discordbot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:223:5)
    at Receiver.receiverOnMessage (C:\Users\stephen\Documents\VS Code\discordbot\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:223:5)
```

**Comment by lntel** [comment]
This has been fixed [here](https://github.com/lntel/Quickcord/commit/dd5ea1dc1e4caa5bf54048c5dfc4049cfe8dd9ff)
