### ISSUE TITLE
Embed color not hex but int

### ISSUE THREAD

**Issue by BigMun** [lntel/Quickcord#2]
```
(node:13536) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.color: Value "#ff1100" is not int.
    at C:\Users\stephen\Documents\VS Code\discordbot\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\Users\stephen\Documents\VS Code\discordbot\node_modules\snekfetch\src\index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:13536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originRequestHandlers\Sequential.js:85:15ated either by throwing inside of an async function without a catch block, or by rejecting a 21
promise which was not handled with .catch(). (rejection id: 2)
(node:13536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In thated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handlede future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lntel** [comment]
As Quickcord uses the Discord.js RichEmbed object, instead of doing
```js
const embed = Quickcord.Embed({
    color: '#ffffff'
});
```

You must replace `#` with `0x`, so it would look like so:

```js
const embed = Quickcord.Embed({
    color: 0xFFFFFF
});
```
